{% set name = "espnet-tts-frontend" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/espnet/espnet_tts_frontend/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 949935ded31327ecd9b80fcfac4c5eedfedcc978d7a6923a8c17b19d165e39d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - g2p-en
    - inflect >=1.0.0
    - jaconv
    - pypinyin
    - python >={{ python_min }}
    - unidecode >=1.0.22

test:
  imports:
    - tacotron_cleaner
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/espnet/espnet_tts_frontend
  summary: 'A tools collection of text frontend for ESPnet tts recipes.'
  license: MIT
  license_file: tacotron_cleaner/LICENSE

extra:
  recipe-maintainers:
    - wietsedv
